name: Deploy to Render

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20.9.0

            - name: Install Dependencies
              run: npm install && cd ./client && npm install

            - name: Build
              run: cd ./client && npm run build

            - name: Debugging
              run: |
                  echo "Current directory: $(pwd)"
                  echo "Contents of the 'client' directory: $(ls -l ./client)"
                  echo "Contents of the 'client/build/static/css' directory: $(ls -l ./client/build/static/css)"
                  echo "Contents of the 'client/build/static/js' directory: $(ls -l ./client/build/static/js)"

            - name: Deploy to Render
              run: |
                  curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
                       -H "Content-Type: application/json" \
                       -d '{"buildCommand": "cd ./client && npm run build", "startCommand": "cd .. && npm start", "staticFiles": {"content-type": "text/css,application/javascript"}}' \
                       https://api.render.com/deploy/srv-cm2dsn8cmk4c73e16shg?key=S77VF2H9tWc
